#!/bin/bash

if [ $# -lt 1 ]; then
  echo "$0 nom_fichier"
  exit 1
elif [ -e "$1.tex" ]; then
  echo "le fichier $1.tex existe déjà"
  exit 1
else
  cp ~/texmf/tex/latex/knonn/modele.tex ./$1.tex
  exit 0
fi
